# Generated by Django 4.1.7 on 2023-04-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources'), ('SALES', 'Sales'), ('MARKETING', 'Marketing'), ('FINANCE', 'Finance'), ('EDU', 'Education'), ('ENG', 'Engineering'), ('HEALTH', 'Healthcare'), ('HOSP', 'Hospitality'), ('ARTS', 'Arts and Entertainment'), ('LAW', 'Legal'), ('SCI', 'Science and Research'), ('GOV', 'Government and Public Administration'), ('MANU', 'Manufacturing'), ('RETAIL', 'Retail'), ('TRANS', 'Transportation and Logistics'), ('AGRI', 'Agriculture'), ('CONSTR', 'Construction'), ('ENV', 'Environmental Services'), ('MEDIA', 'Media and Communications'), ('SOC', 'Social Services')], default='', max_length=250),
        ),
    ]
