# Generated by Django 4.1.7 on 2023-02-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_academic_cv_alter_experince_cv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='logo',
            field=models.ImageField(null=True, upload_to='logos'),
        ),
    ]
