# Generated by Django 4.1.7 on 2023-04-12 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_account_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='Resume',
        ),
    ]
