# Generated by Django 4.1.7 on 2023-04-19 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_account_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='account',
            name='language',
        ),
        migrations.RemoveField(
            model_name='account',
            name='skills',
        ),
    ]
