# Generated by Django 4.1.7 on 2023-03-15 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_jobdetails_companyemail_jobdetails_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='applieddate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
