# Generated by Django 4.1.7 on 2023-04-28 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_account_dob_remove_account_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(choices=[('accounting-finance', 'Accounting & Finance'), ('administrative', 'Administrative'), ('customer-service', 'Customer Service'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('human-resources', 'Human Resources'), ('information-technology', 'Information Technology'), ('marketing', 'Marketing'), ('sales', 'Sales')], default='information-technology', max_length=250),
        ),
    ]
