# Generated by Django 4.1.7 on 2023-03-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_applylist_applieddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='applieddate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
