# Generated by Django 4.1.7 on 2023-03-18 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_applylist_applieddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjobs',
            name='job',
        ),
        migrations.RemoveField(
            model_name='appliedjobs',
            name='user',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='cand',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobdetails',
            name='email',
        ),
        migrations.DeleteModel(
            name='resume',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='job',
        ),
        migrations.RemoveField(
            model_name='savedjobs',
            name='user',
        ),
        migrations.DeleteModel(
            name='AppliedJobs',
        ),
        migrations.DeleteModel(
            name='Applylist',
        ),
        migrations.DeleteModel(
            name='JobDetails',
        ),
        migrations.DeleteModel(
            name='SavedJobs',
        ),
    ]
