# Generated by Django 4.1.7 on 2023-04-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0007_alter_account_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.CharField(blank=True, choices=[('accounting-finance', 'Accounting & Finance'), ('administrative', 'Administrative'), ('customer-service', 'Customer Service'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('human-resources', 'Human Resources'), ('information-technology', 'Information Technology'), ('marketing', 'Marketing'), ('sales', 'Sales')], max_length=250, null=True),
        ),
    ]
