# Generated by Django 4.1.7 on 2023-04-12 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='achidetails',
            fields=[
                ('achi_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('achiname', models.CharField(max_length=100, null=True)),
                ('achiinfo', models.CharField(max_length=100, null=True)),
                ('achidate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='certidetails',
            fields=[
                ('cer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('certiname', models.CharField(max_length=100, null=True)),
                ('cerinfo', models.CharField(max_length=100, null=True)),
                ('certidate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='interdetails',
            fields=[
                ('in_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('interns', models.CharField(max_length=100, null=True)),
                ('internname', models.CharField(max_length=100, null=True)),
                ('interndate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='projectdetails',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('cann_id', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('proname', models.CharField(max_length=100, null=True)),
                ('prodetails', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='resumme',
            fields=[
                ('res_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('carobj', models.TextField(blank=True)),
                ('college', models.CharField(blank=True, max_length=100)),
                ('colcourse', models.CharField(blank=True, max_length=100)),
                ('colpy', models.CharField(blank=True, max_length=100)),
                ('plus', models.CharField(blank=True, max_length=100)),
                ('plusmarks', models.CharField(blank=True, max_length=100)),
                ('pluspy', models.CharField(blank=True, max_length=100)),
                ('ten', models.CharField(blank=True, max_length=100)),
                ('schomarks', models.CharField(blank=True, max_length=100)),
                ('schopy', models.CharField(blank=True, max_length=100)),
                ('refe', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.TextField(blank=True)),
                ('strength', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('lang', models.TextField(blank=True, null=True)),
                ('hob', models.TextField(blank=True, null=True)),
                ('soci', models.CharField(blank=True, max_length=100)),
                ('coun', models.CharField(blank=True, max_length=100)),
                ('status', models.BooleanField(default=0, verbose_name='status')),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
