# Generated by Django 4.1.7 on 2023-04-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumme',
            name='phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
