# Generated by Django 4.1.7 on 2023-03-22 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_rename_user_course_purchase_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='course',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course_purchase',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
