# Generated by Django 4.1.7 on 2023-03-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_courses_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courses',
        ),
    ]
