# Generated by Django 4.1.7 on 2023-03-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedjobs',
            name='is_saved',
            field=models.BooleanField(default=False),
        ),
    ]
