# Generated by Django 4.1.7 on 2023-04-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_feedback_sentiment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='improvements',
            new_name='feedback',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='recommendation',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='satisfaction',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sentiment',
        ),
    ]
