# Generated by Django 4.1.7 on 2023-03-22 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_courses_videos_feedback_course_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='achi',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='address',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='carobj',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='resume',
            name='certi',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='college',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='hob',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='interns',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='lang',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.IntegerField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='plus',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='position',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='projects',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='refe',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='strength',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='ten',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
