# Generated by Django 4.1.7 on 2023-03-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_savedjobs_is_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjobs',
            name='accept',
            field=models.BooleanField(default=True, verbose_name='accept'),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='applied',
            field=models.BooleanField(default=True, verbose_name='applied'),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='reject',
            field=models.BooleanField(default=True, verbose_name='reject'),
        ),
        migrations.AddField(
            model_name='appliedjobs',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
