# Generated by Django 4.1.7 on 2023-04-02 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_rename_improvements_feedback_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applylist',
            name='accept',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='applied',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='education',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='maxsalary',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='minsalary',
        ),
        migrations.RemoveField(
            model_name='applylist',
            name='reject',
        ),
        migrations.AddField(
            model_name='applylist',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applylist',
            name='recruiter_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applylist',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('rejected', 'Rejected'), ('selected', 'Selected')], default='applied', max_length=10),
        ),
    ]
