# Generated by Django 4.1.7 on 2023-03-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_applylist_accept_applylist_applied_applylist_reject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedJobs',
        ),
    ]
