# Generated by Django 4.1.7 on 2023-04-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_remove_applylist_accept_remove_applylist_applied_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applylist',
            name='recruiter_notes',
        ),
        migrations.AlterField(
            model_name='applylist',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=8),
        ),
    ]
