# Generated by Django 4.1.7 on 2023-03-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_delete_appliedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='desp',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='videos',
            name='title',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
