# Generated by Django 4.1.7 on 2023-03-28 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0006_videos_desp_alter_videos_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='course',
        ),
    ]
