# Generated by Django 4.1.7 on 2023-04-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='amount',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
