# Generated by Django 4.1.7 on 2023-03-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_remove_feedback_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
