# Generated by Django 4.1.7 on 2023-04-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_alter_courses_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('negative_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('neutral_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('compoud_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_reviews', models.IntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Employee.feedback')),
            ],
        ),
    ]
