# Generated by Django 4.1.7 on 2023-05-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_alter_sentiment_compoud_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('ACCEPTED', 'Accepted'), ('IN REVIEW', 'In Review'), ('APPROVED', 'Approved'), ('ON HOLD', 'On Hold'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
