# Generated by Django 4.1.7 on 2023-03-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_alter_feedback_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applylist',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume'),
        ),
    ]
