# Generated by Django 4.1.7 on 2023-03-30 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_alter_applylist_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applylist',
            name='resume',
        ),
    ]
