# Generated by Django 4.1.7 on 2023-03-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0012_remove_applylist_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='applylist',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume'),
        ),
    ]
