# Generated by Django 4.1.7 on 2023-03-30 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_applylist_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='resume',
        ),
    ]
