# Generated by Django 4.1.7 on 2023-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0015_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applylist',
            name='Resume',
        ),
        migrations.AddField(
            model_name='applylist',
            name='resumes',
            field=models.FileField(blank=True, null=True, upload_to='AppliedResume'),
        ),
    ]
