# Generated by Django 4.1.7 on 2023-03-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='startdate',
        ),
    ]
