# Generated by Django 4.1.7 on 2023-03-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_remove_jobdetails_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='tagline',
            field=models.CharField(default='', max_length=100),
        ),
    ]
