# Generated by Django 4.1.7 on 2023-04-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_alter_jobdetails_jobtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Applicants',
        ),
    ]
