# Generated by Django 4.1.7 on 2023-04-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_alter_jobdetails_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='category',
            field=models.CharField(choices=[('accounting-finance', 'Accounting & Finance'), ('administrative', 'Administrative'), ('customer-service', 'Customer Service'), ('engineering', 'Engineering'), ('healthcare', 'Healthcare'), ('human-resources', 'Human Resources'), ('information-technology', 'Information Technology'), ('marketing', 'Marketing'), ('sales', 'Sales')], default='', max_length=250),
        ),
    ]
