# Generated by Django 4.1.7 on 2023-04-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_alter_jobdetails_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='Resume',
            field=models.FileField(blank=True, null=True, upload_to='Resume'),
        ),
        migrations.AddField(
            model_name='jobdetails',
            name='skills',
            field=models.CharField(default='', max_length=40),
        ),
    ]
