# Generated by Django 4.1.7 on 2023-05-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0008_applicants_resume_jobdetails_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicants',
            name='status',
        ),
    ]
